name: labwork

on: push

jobs:
  build:
    name: "Ubuntu/18.04/Static/X64/Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Work Dir
        run: mkdir build
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        working-directory: ./build
        run: cmake --build . -j --config Release
      - name: Test
        working-directory: ./build
        run: ctest -j -C Release
